### PR TITLE
background of homepage fixed

### LINKED ISSUE #31: In Homepage I want add a background instead of a text HomePage.
This will make app look more attractive .

### PR DESCRIPTION
**Pull request by Shreya-1305**
I have added a background and fixedfew bugs in searching books as well .

### CODE REVIEW

**Comment by Shreya-1305** [comment]
@sunny7899 please review and merge my PR .  Thankyou !

**Comment by Shreya-1305** [comment]
@sunny can you please add girlscript-ext and level label . as none of my PR is getting counted for girlscript. Thankyou !

**Comment by sunny** [comment]
@Shreya-1305 Please ping @sunny7899, not @sunny 🙏🏻

**Comment by Shreya-1305** [comment]
@sunny7899 can you please add level label to my PR . if you don't add level label it wont be counted in girlscript . I have created about 3PRs and none of them are getting counted because level label is not assigned . They have been counted in hacktober but not girlscript . 

you can assign level label like : level 1 , level 2 or level 3. 

Please add this labels for all the 3 PRS.

Thankyou !

**Comment by sunny7899** [comment]
@Shreya-1305  pls share other PR links here

**Comment by Shreya-1305** [comment]
@sunny Thankyou for adding label .
In this PR please add gssoc-ext label also.

Here are the links to other 2 PRs 

1) https://github.com/angulardevelopment/book-rating-app-assignment/pull/30

2) In this PR I will need gssoc-ext and level label .
https://github.com/angulardevelopment/book-rating-app-assignment/pull/24#issuecomment-2434293213

Thankyou for ypur response !



Here is the example from my previous PR which got accepted in girlscript .  

Screenshot 2024-11-03 072626

**Comment by sunny7899** [comment]
@Shreya-1305  sure

**Comment by Shreya-1305** [comment]
@sunny7899 Thankyou very much

**Pull request merged**
