### PR TITLE
Jenny auth br

### LINKED ISSUE #15: Work on updating and Deleting a user api
This feature allows user details to be updated or a user to be deleted

### PR DESCRIPTION
**Pull request by Jennifer-tech**
Worked on an api for updating and deleting of users

### CODE REVIEW

**Comment by Jennifer-tech** [comment]
@sunny7899

**Comment by sunny7899** [comment]
@Jennifer-tech so you worked in this issue https://github.com/angulardevelopment/book-rating-app-assignment/issues/18. Can you please update the message its showing patient updated successfully

**Comment by Jennifer-tech** [comment]
@sunny7899, okay I will update it in my next PR

**Comment by sunny7899** [comment]
@Jennifer-tech can you please resolve the conflict

**Comment by Jennifer-tech** [comment]
@sunny7899 resolved

**Pull request merged**
