### PR TITLE
Create and update book ratings

### LINKED ISSUE #11: Page that allows user to add or edit a book rating
What you will get : 

- Page that is ready to be either rate the book rating or update the existing book ratings
- Input contains of : title, author, publisher, published date, edition, summary/description, page count, ratings, review, review date.
- Save and Update function

P.S. No server-side interaction or external API calls

### PR DESCRIPTION
**Pull request by aetherfaye1009**
### What you get : 
- Create and Update Book Ratings: The app allows users to create a new book rating or update an existing one, differentiating between actions based on URL parameters.
- Action Identification:
When params from the URL has valid `bookRatingID`, it enables the updating of an existing book rating.
Otherwise, it creates a new book rating instead.

### User Input Fields:
The application includes input fields for comprehensive book details:
- Title
- Author
- Publisher
- Published Date
- Edition
- Summary
- Page Counts
- Ratings
- Review
- Review Date

### Implementation Details:
- Condition Handling: All necessary conditions for creating or updating a book rating are prepared within the save function, ensuring smooth operation.
- API Integration: The app is designed to allow users to easily implement their own create or update API calls directly within the save function.
 
### User Interface:
- Simple and user friendly design.

### Code Quality Improvements:
- Ensured code follows best practices for maintainability and readability.
- Added comments and documentation where necessary for clarity.

### Testing:
- Ensured that all new features work seamlessly with existing code

Issues: #11

Let me know if there is anything you want me to add.

### CODE REVIEW

**Comment by aetherfaye1009** [comment]
image
image
image
image
image

**Comment by aetherfaye1009** [comment]
Please assign me the hacktoberfest tag if you are okay with it.

**Comment by sunny7899** [comment]
@aetherfaye1009   can u resolve merge conflict please

**Comment by aetherfaye1009** [comment]
@sunny7899  done.

**Pull request merged**
