### PR TITLE
Search for the books from the api 

### LINKED ISSUE #28: I want to add a feature of fetching books from google books api when searched in search bar
When user will search for a particular book from the search bar in the navbar . It will display all the books with that particular keyord in it. and display on the screen . 

Please assign thi issue to me . Thankyou !

### PR DESCRIPTION
**Pull request by Shreya-1305**
fixes #28

I have created a context from where the books can be fetched in future as well. 

I can make changes if you want; please let me know your recommendations. Please review my PR and add label of hacktoberfest-accepted and gssoc-ext .

Thankyou !

### CODE REVIEW

**Comment by Shreya-1305** [comment]
@sunny please review and merge my PR .

**Comment by sunny** [comment]
I’m not in this project, please ping @sunny7899 instead.

**Comment by Shreya-1305** [comment]
@sunny7899 if possible can you please add label of level  for girlscript . otherwise my PR won't be counted. you can add any level . level 1  , level 2 or level3 . Thankyou ! .

**Comment by Shreya-1305** [comment]
Can you please add level label  , if possible . you can give level 1 to 3 according to my work .  Thankyou !

**Pull request merged**
