### PR TITLE
SUBMITTED

### PR DESCRIPTION
**Pull request by Swastik200**
PLEASE CHECK AND CONFIRM
B12
B11

### CODE REVIEW

**Comment by sunny7899** [comment]
@Swastik200 Do you know any framework like angular or react? Can you create that app using framework?

**Comment by Swastik200** [comment]
Sorry not exactly
I just used html css and js
However will learn any framework
But as of now plz forgive

**Comment by sunny7899** [comment]
please move it to js-30 project or html-templates  and close PR from here @Swastik200

**Comment by Swastik200** [comment]
Ok, I will do it.

**Comment by Swastik200** [comment]
Done
Please check and confirm

**Pull request closed without merging**
